// Общие стили для всего Dashboard
const styles = {
  container: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#EFE3D7',
    fontFamily: 'Montserrat, sans-serif',
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#5A6E26',
    display: 'flex',
    flexDirection: 'column',
    padding: '30px 20px',
    boxShadow: '4px 0 15px rgba(0,0,0,0.05)',
    zIndex: 10,
  },
  logoArea: {
    marginBottom: '35px',
    textAlign: 'center',
  },
  separator: {
    height: '1px',
    backgroundColor: 'rgba(239, 227, 215, 0.2)',
    width: '100%',
    marginBottom: '20px',
  },
  greetingBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  },
  greetingTime: {
    color: '#EFE3D7',
    fontSize: '13px',
    fontWeight: '500',
    opacity: 0.8,
  },
  greetingName: {
    color: '#EFE3D7',
    fontSize: '17px',
    fontWeight: '800',
    letterSpacing: '0.5px',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    flexGrow: 1,
  },
  navItem: {
    color: '#EFE3D7',
    fontSize: '16px',
    fontWeight: '600',
    padding: '15px 20px',
    borderRadius: '15px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    opacity: 0.8,
  },
  navItemHover: {
    opacity: 1,
    backgroundColor: 'rgba(239, 227, 215, 0.1)',
    transform: 'translateX(5px)',
  },
  navItemActive: {
    color: '#7A2F2F',
    backgroundColor: '#EFE3D7',
    fontSize: '16px',
    fontWeight: '700',
    padding: '15px 20px',
    borderRadius: '15px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0,0,0,0.1)',
  },
  logoutBtn: {
    color: '#EFE3D7',
    textAlign: 'center',
    padding: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    borderTop: '1px solid rgba(239, 227, 215, 0.2)',
    marginTop: 'auto',
    transition: 'opacity 0.2s',
  },
  mainContent: {
    flexGrow: 1,
    padding: '40px 50px',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
  },
  pageTitle: {
    color: '#7A2F2F',
    fontSize: '32px',
    fontWeight: '800',
    margin: 0,
  },
  addButton: {
    backgroundColor: '#7A2F2F',
    color: '#EFE3D7',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '25px',
    fontSize: '16px',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 4px 15px rgba(122, 47, 47, 0.3)',
    transition: 'transform 0.2s, background-color 0.2s',
  },
  summaryGrid: {
    display: 'flex',
    gap: '20px',
    marginBottom: '30px',
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: '25px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
  },
  summaryLabel: {
    color: '#A68E7A',
    fontSize: '13px',
    fontWeight: '700',
    margin: '0 0 10px 0',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  summaryValue: {
    color: '#5A6E26',
    fontSize: '32px',
    fontWeight: '800',
    margin: 0,
  },
  summaryValueHighlight: {
    color: '#7A2F2F',
    fontSize: '26px',
    fontWeight: '800',
    margin: 0,
  },
  emptyPaymentContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '2px',
  },
  emptyPaymentIcon: {
    fontSize: '28px',
    marginBottom: '4px',
  },
  emptyPaymentText: {
    color: '#A68E7A',
    fontSize: '18px',
    fontWeight: '700',
    margin: 0,
  },
  emptyPaymentHint: {
    color: '#C4B3A3',
    fontSize: '13px',
    fontWeight: '500',
    margin: 0,
    fontStyle: 'italic',
  },
  emptyListContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '50px 20px',
    gap: '8px',
  },
  emptyListIcon: {
    fontSize: '48px',
    marginBottom: '8px',
  },
  emptyListTitle: {
    color: '#7A2F2F',
    fontSize: '18px',
    fontWeight: '700',
    margin: 0,
    textAlign: 'center',
  },
  emptyListHint: {
    color: '#A68E7A',
    fontSize: '14px',
    fontWeight: '500',
    margin: 0,
    textAlign: 'center',
  },
  listSection: {
    backgroundColor: '#FFFFFF',
    padding: '30px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
  },
  sectionTitle: {
    color: '#7A2F2F',
    fontSize: '20px',
    fontWeight: '800',
    margin: '0 0 20px 0',
  },
  subsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  subCard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px',
    backgroundColor: '#F9F6F0',
    border: '1px solid rgba(166, 142, 122, 0.2)',
    borderRadius: '15px',
    transition: 'transform 0.2s',
  },
  subInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  subName: {
    color: '#5A6E26',
    fontSize: '18px',
    fontWeight: '800',
    margin: 0,
  },
  subDetails: {
    color: '#A68E7A',
    fontSize: '14px',
    fontWeight: '500',
    margin: 0,
  },
  subPriceAction: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  price: {
    color: '#7A2F2F',
    fontSize: '20px',
    fontWeight: '800',
  },
  actions: {
    display: 'flex',
    gap: '10px',
  },
  actionBtn: {
    background: 'none',
    border: 'none',
    fontSize: '18px',
    cursor: 'pointer',
    opacity: 0.6,
    transition: 'opacity 0.2s',
  },
  chartsRow: {
    display: 'flex',
    gap: '24px',
    marginBottom: '30px',
  },
  chartCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: '28px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
    display: 'flex',
    flexDirection: 'column',
  },
  chartSubtitle: {
    color: '#A68E7A',
    fontSize: '13px',
    fontWeight: '500',
    margin: '0 0 20px 0',
  },
  chartContainerSquare: {
    height: '320px',
    width: '100%',
  },
  chartEmptyState: {
    backgroundColor: '#FFFFFF',
    padding: '80px 40px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  legendContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginTop: '20px',
    padding: '16px 0 0',
    borderTop: '1px solid rgba(166,142,122,0.15)',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    backgroundColor: '#F9F6F0',
    borderRadius: '10px',
    fontSize: '13px',
  },
  legendDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  legendLabel: {
    color: '#5A6E26',
    fontWeight: '700',
  },
  legendValue: {
    color: '#A68E7A',
    fontWeight: '600',
  },
  barDetailsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '20px',
    padding: '16px 0 0',
    borderTop: '1px solid rgba(166,142,122,0.15)',
  },
  barDetailRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  barDetailRank: {
    color: '#A68E7A',
    fontSize: '12px',
    fontWeight: '800',
    minWidth: '24px',
  },
  barDetailName: {
    color: '#5A6E26',
    fontSize: '14px',
    fontWeight: '700',
    minWidth: '100px',
  },
  barDetailBarBg: {
    flex: 1,
    height: '8px',
    backgroundColor: '#F0EAE2',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  barDetailBarFill: {
    height: '100%',
    backgroundColor: '#7A2F2F',
    borderRadius: '4px',
    transition: 'width 0.6s ease',
  },
  barDetailPrice: {
    color: '#7A2F2F',
    fontSize: '14px',
    fontWeight: '800',
    minWidth: '80px',
    textAlign: 'right',
  },
  exportSection: {
    backgroundColor: '#FFFFFF',
    padding: '30px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
  },
  exportInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '20px',
    backgroundColor: 'rgba(90, 110, 38, 0.06)',
    borderRadius: '14px',
    marginBottom: '24px',
    border: '1px solid rgba(90, 110, 38, 0.12)',
  },
  exportInfoIcon: {
    fontSize: '32px',
    backgroundColor: '#FFFFFF',
    width: '52px',
    height: '52px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '14px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    flexShrink: 0,
  },
  exportInfoTitle: {
    color: '#5A6E26',
    fontSize: '16px',
    fontWeight: '800',
    margin: '0 0 4px 0',
  },
  exportInfoDesc: {
    color: '#A68E7A',
    fontSize: '14px',
    fontWeight: '500',
    margin: 0,
  },
  exportTableWrapper: {
    overflowX: 'auto',
    borderRadius: '14px',
    border: '1px solid rgba(166, 142, 122, 0.15)',
  },
  exportTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontFamily: 'Montserrat, sans-serif',
  },
  exportTh: {
    backgroundColor: '#F9F6F0',
    color: '#7A2F2F',
    fontSize: '12px',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    padding: '14px 20px',
    textAlign: 'left',
    borderBottom: '2px solid rgba(166, 142, 122, 0.15)',
  },
  exportTd: {
    padding: '14px 20px',
    fontSize: '15px',
    fontWeight: '500',
    color: '#5A6E26',
    borderBottom: '1px solid rgba(166, 142, 122, 0.08)',
  },
  exportTdName: {
    fontWeight: '700',
    color: '#5A6E26',
  },
  exportTdPrice: {
    fontWeight: '800',
    color: '#7A2F2F',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(90, 110, 38, 0.35)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    animation: 'fadeIn 0.2s ease-out',
  },
  modalContent: {
    backgroundColor: '#FFFCF8',
    padding: '0',
    borderRadius: '28px',
    width: '480px',
    maxWidth: '90vw',
    boxShadow: '0 25px 60px rgba(0,0,0,0.15), 0 0 0 1px rgba(166, 142, 122, 0.1)',
    overflow: 'hidden',
    animation: 'slideUp 0.3s ease-out',
  },
  modalHeader: {
    background: 'linear-gradient(135deg, #5A6E26 0%, #7A8F36 100%)',
    padding: '32px 36px 28px',
    textAlign: 'center',
  },
  modalIconCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    backgroundColor: 'rgba(239, 227, 215, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 16px',
    backdropFilter: 'blur(10px)',
  },
  modalIconEmoji: {
    fontSize: '28px',
  },
  modalTitle: {
    color: '#FFFCF8',
    fontSize: '24px',
    fontWeight: '800',
    margin: '0 0 6px 0',
    letterSpacing: '-0.5px',
  },
  modalSubtitle: {
    color: 'rgba(239, 227, 215, 0.8)',
    fontSize: '14px',
    fontWeight: '500',
    margin: 0,
  },
  modalDivider: {
    height: '3px',
    background: 'linear-gradient(90deg, #7A2F2F, #5A6E26, #7A2F2F)',
    opacity: 0.3,
  },
  modalForm: {
    padding: '28px 36px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  fieldRow: {
    display: 'flex',
    gap: '16px',
  },
  fieldLabel: {
    color: '#7A2F2F',
    fontSize: '13px',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  fieldIcon: {
    fontSize: '14px',
  },
  modalInput: {
    padding: '14px 18px',
    borderRadius: '14px',
    border: '2px solid rgba(166, 142, 122, 0.2)',
    fontSize: '16px',
    fontWeight: '600',
    color: '#5A6E26',
    outline: 'none',
    backgroundColor: '#F9F6F0',
    fontFamily: 'Montserrat, sans-serif',
    transition: 'border-color 0.2s, box-shadow 0.2s',
    width: '100%',
    boxSizing: 'border-box',
  },
  modalSelect: {
    padding: '14px 18px',
    borderRadius: '14px',
    border: '2px solid rgba(166, 142, 122, 0.2)',
    fontSize: '16px',
    fontWeight: '600',
    color: '#5A6E26',
    outline: 'none',
    backgroundColor: '#F9F6F0',
    fontFamily: 'Montserrat, sans-serif',
    cursor: 'pointer',
    transition: 'border-color 0.2s, box-shadow 0.2s',
    width: '100%',
    boxSizing: 'border-box',
    appearance: 'none',
    WebkitAppearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%23A68E7A' d='M6 8L1 3h10z'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 16px center',
    paddingRight: '40px',
  },
  modalActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '8px',
  },
  modalBtnCancel: {
    flex: 1,
    backgroundColor: 'transparent',
    color: '#A68E7A',
    padding: '14px 20px',
    border: '2px solid rgba(166, 142, 122, 0.25)',
    borderRadius: '14px',
    fontWeight: '700',
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontFamily: 'Montserrat, sans-serif',
  },
  modalBtnCancelHover: {
    backgroundColor: 'rgba(166, 142, 122, 0.08)',
    borderColor: 'rgba(166, 142, 122, 0.4)',
  },
  modalBtnSubmit: {
    flex: 2,
    backgroundColor: '#7A2F2F',
    color: '#FFFCF8',
    padding: '14px 28px',
    border: 'none',
    borderRadius: '14px',
    fontWeight: '700',
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontFamily: 'Montserrat, sans-serif',
    boxShadow: '0 4px 15px rgba(122, 47, 47, 0.25)',
    letterSpacing: '0.3px',
  },
  modalBtnSubmitHover: {
    backgroundColor: '#8B3636',
    transform: 'translateY(-1px)',
    boxShadow: '0 6px 20px rgba(122, 47, 47, 0.35)',
  },
  settingsToast: {
    padding: '14px 24px',
    borderRadius: '14px',
    color: '#FFFCF8',
    fontWeight: '700',
    fontSize: '15px',
    marginBottom: '24px',
    display: 'flex',
    alignItems: 'center',
    boxShadow: '0 4px 15px rgba(0,0,0,0.1)',
    animation: 'slideUp 0.3s ease-out',
  },
  settingsCard: {
    backgroundColor: '#FFFFFF',
    padding: '28px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
    marginBottom: '24px',
  },
  settingsCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '20px',
    paddingBottom: '16px',
    borderBottom: '1px solid rgba(166,142,122,0.15)',
  },
  settingsCardIcon: {
    fontSize: '28px',
    width: '48px',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9F6F0',
    borderRadius: '14px',
    flexShrink: 0,
  },
  settingsCardTitle: {
    color: '#7A2F2F',
    fontSize: '20px',
    fontWeight: '800',
    margin: 0,
  },
  settingsProfileGrid: {
    display: 'flex',
    gap: '20px',
  },
  settingsProfileItem: {
    flex: 1,
    padding: '16px 20px',
    backgroundColor: '#F9F6F0',
    borderRadius: '14px',
    border: '1px solid rgba(166,142,122,0.1)',
  },
  settingsProfileLabel: {
    display: 'block',
    color: '#A68E7A',
    fontSize: '12px',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    marginBottom: '6px',
  },
  settingsProfileValue: {
    display: 'block',
    color: '#5A6E26',
    fontSize: '16px',
    fontWeight: '700',
  },
  settingsFormsRow: {
    display: 'flex',
    gap: '24px',
  },
  settingsForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  settingsSubmitBtn: {
    backgroundColor: '#7A2F2F',
    color: '#FFFCF8',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '14px',
    fontSize: '15px',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: 'Montserrat, sans-serif',
    boxShadow: '0 4px 15px rgba(122, 47, 47, 0.25)',
    transition: 'all 0.2s ease',
    marginTop: '4px',
  },
  settingsTelegramDesc: {
    color: '#A68E7A',
    fontSize: '15px',
    fontWeight: '500',
    margin: '0 0 20px 0',
    lineHeight: '1.5',
  },
  settingsTelegramLinked: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    backgroundColor: 'rgba(90, 110, 38, 0.06)',
    borderRadius: '14px',
    border: '1px solid rgba(90, 110, 38, 0.12)',
  },
  settingsTelegramStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  settingsTelegramDot: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
    backgroundColor: '#5A6E26',
    boxShadow: '0 0 8px rgba(90, 110, 38, 0.4)',
  },
  settingsTelegramStatusText: {
    color: '#5A6E26',
    fontSize: '15px',
    fontWeight: '600',
  },
  settingsUnlinkBtn: {
    backgroundColor: 'transparent',
    color: '#7A2F2F',
    border: '2px solid rgba(122, 47, 47, 0.25)',
    padding: '10px 20px',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: 'Montserrat, sans-serif',
    transition: 'all 0.2s ease',
  },
  settingsTelegramForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  settingsTelegramInputRow: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
  },
  settingsTelegramHint: {
    color: '#A68E7A',
    fontSize: '13px',
    fontWeight: '500',
    margin: 0,
    fontStyle: 'italic',
  },
  passwordRulesContainer: {
    width: '100%',
    padding: '8px 10px 0',
    color: '#7A2F2F',
    fontSize: '13px',
    textAlign: 'left',
    opacity: 0.9,
    fontWeight: '600',
  },
  passwordRulesList: {
    margin: 0,
    paddingLeft: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
};

export default styles;
