"""Add password reset fields

Revision ID: 2afc95ddf55b
Revises: a7a5186d9664
Create Date: 2026-04-09 15:39:14.118282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afc95ddf55b'
down_revision: Union[str, Sequence[str], None] = 'a7a5186d9664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
